[SW-2500] Temporarily Disable Beta Constraints Tests
h2oai/sparkling-water pull request #2420
Opened 2020-12-14 13:03 UTC by mn-mikke

https://h2oai.atlassian.net/browse/SW-2500

2020-12-14 14:03 UTC, satai commented on py/tests/unit/with_runtime_sparkling/test_glm.py
> -def testBetaConstraintsAffectResult(spark, prostateDataset):
Wouldn't 
@unittest.skip("SW-2500")
work here?

2020-12-14 14:14 UTC, satai approved these changes

2020-12-14 18:41 UTC, honzasterba requested changes
there has to be a better way than this:
are failing tests such a problem influencing other test? then we should fix the test-framework
is using a @ignore annotation not possible? we should fix the test framework

2020-12-14 19:36 UTC, mn-mikke commented
@honzasterba @satai Thanks guys for your comments, much appreciated! I was just too lazy to read pytest documentation.

2020-12-15 10:23 UTC, honzasterba approved these changes

2020-12-15 13:38 UTC, merged