[SW-2787] Change license to AGPL v3
h2oai/sparkling-water pull request #5624
Opened 2023-06-01 21:26 UTC by krasinski

closes #5623

2023-06-02 08:44 UTC, mn-mikke commented on py-scoring/conda/h2o_pysparkling_scoring_SUBST_SPARK_MAJOR_VERSION/meta.yaml
> +  license: AGPL-3
Shouldn't this be `GNU Affero General Public License v3`? https://github.com/h2oai/h2o-3/pull/15533/files#diff-88f12fed5fbaae7ae5bb9d65df632b469aad6f69e7bcadcbfda31939b01c47c3R25

2023-06-02 08:44 UTC, mn-mikke commented on py/conda/h2o_pysparkling_SUBST_SPARK_MAJOR_VERSION/meta.yaml
> +  license: AGPL-3
ditto

2023-06-02 18:54 UTC, wendycwong reviewed
Interested to see that you actually removed the license header from some files.  This will make the next license change easier.

Marekn/MichalM:  Please approve.

2023-06-03 01:03 UTC, mmalohlava requested changes
Hold on mee, please.

2023-06-19 10:48 UTC, mn-mikke commented
We will continue with Apache 2.0 license.

2023-06-19 10:48 UTC, closed without merging